FROM python:3.11-slim-bookworm
WORKDIR /service_1_py
RUN apt update && apt install -y procps curl coreutils
RUN curl -L "https://github.com/docker/compose/releases/download/v2.30.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose
RUN pip3 install flask requests
COPY main.py .
ENTRYPOINT ["python3", "/service_1_py/main.py"]


