FROM python:3.11-slim-bookworm
WORKDIR /service_1_py
RUN apt update && apt install -y procps
RUN pip3 install flask requests
COPY main.py .
EXPOSE 8199
ENTRYPOINT ["python3", "/service_1_py/main.py"]


